company/company/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('department.urls'))
]

company/department/urls.py
from django.conf.urls import url
from . import views

app_name='department'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^department/add/$', views.saveData.as_view(), name='saves'),
    url(r'department/(?P<pk>[0-9]+)/$', views.EditData.as_view(), name='edit'),
    url(r'department/(?P<pk>[0-9]+)/delete/$', views.deleteData.as_view(), name='deletes'),
]

company/department/models.py
from django.db import models
from django.urls import reverse

class Department(models.Model):
    dept_name = models.CharField(max_length=100)

    def __str__(self):
        return  self.dept_name

    def get_absolute_url(self):
        return  reverse('department:index')


class Employee(models.Model):
    dep_id = models.ForeignKey(Department,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return (self.first_name+" "+self.last_name)

company/department/views.py
from django.shortcuts import render

from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from .models import  Department



class IndexView(ListView):
    template_name = 'department/index.html'
    context_object_name = 'dep_list'

    def get_queryset(self):
        #return Department.objects.all()
        return Department.objects.raw('select * from department_department d,department_employee e where d.id=e.dep_id_id')



class saveData(CreateView):
    model = Department
    fields = ['dept_name']
    success_url = reverse_lazy('department:index')


class EditData(UpdateView):
    model = Department
    fields = ['dept_name']



class deleteData(DeleteView):
    model = Department
    success_url = reverse_lazy('department:index')

company/department/templates/department/base.html
<html>
<head>

    <title>College Aplicatin</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

</head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">WebSiteName</a>
        </div>
        <ul class="nav navbar-nav">

          <li><a href="{% url 'department:index' %}">Veiw</a></li>
            <li><a href="{% url 'department:saves' %}">Add</a></li>

        </ul>
      </div>
    </nav>
</body>

<div class="container">
    {% block body%}
    {% endblock%}
</div>


</html>

company/department/templates/department/department_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

company/department/templates/department/department_form.html
{% extends 'department/base.html' %}

 {% block body %}

<div>
    <form method="post">
          {% csrf_token %}
        <div>
            <label>Department Name</label> {{form.dept_name}}
        </div>
        <div>
            <button type="submit">submit</button>
        </div>
    </form>

</div>




{% endblock %}

company/department/templates/department/index.html
{% extends 'department/base.html' %}

 {% block body %}

{% if dep_list %}
    <div class="container">
      <h2>Display Dipartment</h2>

            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Department Name</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Action</th>

                  </tr>
                </thead>
                <tbody>
                   {% for list in dep_list %}
                      <tr>
                          <td>{{list.id}}</td>
                          <td>{{list.dept_name}}</td>
                           <td>{{list.first_name}}</td>
                           <td>{{list.last_name}}</td>
                          <td><a href="{% url 'department:edit' list.id %}">Edit</a>/<a href="{% url 'department:deletes' list.id %}">Delete</a></td>
                </tr></td>
                      </tr>
                   {% endfor %}
                </tbody>
            </table>

    </div>
{% else %}
    <h2>No Record Found</h2>
{% endif %}

{%endblock%}